# Generated by Django 5.2 on 2025-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='امتیاز کاربر از ۰ تا ۵'),
        ),
    ]
