# Generated by Django 5.2 on 2025-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_currenc_3ed6c4_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='bot2_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
