# Generated by Django 5.2 on 2025-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_is_completed_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='امتیاز از 1 تا 5 ستاره'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='مسدودسازی کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='امتیاز کاربر از 0 تا 5'),
        ),
    ]
