# Generated by Django 5.2 on 2025-05-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_username_alter_user_is_verified'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_currenc_3ed6c4_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, help_text='Admin currently handling this order', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='lock_acquired_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the order was reserved', null=True),
        ),
        migrations.AlterField(
            model_name='chatprompt',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['currency', 'is_buy', 'status', 'assigned_admin', 'lock_acquired_at', 'expires_at'], name='core_order_currenc_c5f91c_idx'),
        ),
    ]
