# Generated by Django 5.2 on 2025-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chatprompt_status_alter_chatprompt_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(default=0.0, help_text='امتیاز کاربر از 0 تا 5 (قابل نیم\u200cستاره)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='امتیاز کاربر از 0.0 تا 5.0 (نیم\u200cستاره مجاز)', max_digits=2),
        ),
    ]
