# Generated by Django 5.2 on 2025-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_feedback_rating_alter_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
